import { deriveKeypairFromIkm, exportRawPublicKey } from "./hpke";
import type { IdentityKeypair, PublicKeyString } from "./types";
import { encodePubkey } from "./wire";

type IdentityImpl = {
  publicKey: CryptoKey;
  privateKey: CryptoKey;
  publicKeyRaw: Uint8Array;
  publicKeyString: PublicKeyString;
};

/**
 * Test-only: derive an IdentityKeypair from input keying material.
 *
 * Throws unless NODE_ENV === "test". Used by interop tests to reproduce the
 * deterministic keypair generated by an external HPKE implementation
 * (RFC 9180 §7.1.3 specifies deterministic DeriveKeyPair from IKM).
 */
export async function __test_only_identityFromIKM(ikm: Uint8Array): Promise<IdentityKeypair> {
  if (process.env.NODE_ENV !== "test") {
    throw new Error("__test_only_identityFromIKM: test-only helper");
  }
  const kp = await deriveKeypairFromIkm(ikm);
  const publicKeyRaw = await exportRawPublicKey(kp.publicKey);
  const publicKeyString = encodePubkey(publicKeyRaw) as PublicKeyString;
  const impl: IdentityImpl = {
    publicKey: kp.publicKey,
    privateKey: kp.privateKey,
    publicKeyRaw,
    publicKeyString,
  };
  return impl as unknown as IdentityKeypair;
}
